Iter13
AntonNikol/go-shortener pull request #18
Opened 2023-02-07 16:19 UTC by AntonNikol

2023-02-09 17:53 UTC, Barugoo commented on cmd/shortener/main.go
> +1 Как в хендлере определить какая реализация репозитория сейчас используется
А хэндлер и не должен это знать, в этом весь смысл. У нас реализация абстрагирована интерфейсом от вызывающего ее кода специально, чтобы эту реализацию можно было спокойно менять при необходимости - до тех пор пока интерфейс реализуется все будет ОК

2023-02-09 17:55 UTC, Barugoo commented on cmd/shortener/main.go
> +2 Может быть хендлеры в файле handler.go называть с постфиксом handler? DBPingHandler и т.д..
Почему бы и нет

2023-02-09 18:03 UTC, Barugoo commented on cmd/shortener/main_test.go
> +//}
Давай убирать закомменченный код из репы

2023-02-09 18:04 UTC, Barugoo commented on internal/app/handlers/handler.go
> +	//}
Тоже самое про закомменченный код

2023-02-09 18:07 UTC, Barugoo commented on internal/app/handlers/handler.go
> +		if errors.Is(err, postgres.ErrUniqueViolation) {
Здесь у тебя течет абстракция - ты проверяешь ошибку конкретной реализации хранилки, хотя под капотом интерфейса может быть, например, хранилка в памяти.

Давай объявим в пакете `repository` собственные ошибки для случаев когда запись не найдена, или когда произошел конфликт при записи:
```go
var (
    ErrNotFound = errors.New("not found")
    ErrAlreadyExists = errors.New("already exists")
)
``` 
и будем возвращать эти ошибки из методов хранилки, а здесь проверять.

2023-02-09 18:16 UTC, Barugoo commented on internal/app/handlers/handler.go
> +	if err != nil {
Уменьшаем вложенность:
```go
item, err = h.repository.AddItem(c.Request().Context(), item)
if err != nil && !errors.Is(err, repository.ErrAlreadyExists) {
    // а вот пятисотки логгировать как раз надо
    log.Printf("unable to add item %v in repo: %v", item, err)
    return c.String(http.StatusInternalServerError, h.baseURL+"/"+item.ID)
}
if errors.Is(err, repository.ErrAlreadyExists) {
    // нам незачем логгировать ошибки 4хх - иначе тогда любой клиент сможет хранилку логов задудосить
    return c.String(http.StatusConflict, h.baseURL+"/"+item.ID)
}

2023-02-09 18:18 UTC, Barugoo commented on internal/app/handlers/handler.go
> +		log.Printf("handler CreateItemJSON json parsing error %v", err)
Тоже логи убираем

2023-02-09 18:22 UTC, Barugoo commented on internal/app/handlers/handler.go
> +	}
Не факт, что ошибка здесь вернется Not Found. В случае реализации хранилки в памяти - да, там ничего сломаться не может и ошибка будет всегда означать нот фаунд, какая бы она не пришла. Но если там под капотом находится любой ввод-вывод (файл, база), то ошибку этот ввод-вывод всегда может вернуть, поэтому нам надо различать not found и разрывы соединения/поломки/неправильные SQL-запросы и тд. 

В таких случаях мы создаем экземпляры ошибок которые мы предполагаем получить согласно нашей логике, а все остальные интерпретируем как 500:
```go
item, err := h.repository.GetItemByID(c.Request().Context(), id)
if err != nil && !errors.Is(err, repository.ErrNotFound) {
    log.Printf("unable to get item %v from repo: %v", id, err)
    return c.String(http.StatusInternalServerError, h.baseURL+"/"+id)
}
if errors.Is(err, repository.ErrNotFound) {
    return c.String(http.StatusNotFound, "Ссылка не найдена")
}

c.Response().Header().Set("Location", item.FullURL)
return c.String(http.StatusTemporaryRedirect, "")

2023-02-09 18:23 UTC, Barugoo commented on internal/app/handlers/handler.go
> +		return echo.NewHTTPError(http.StatusInternalServerError, IntServErr)
Это bad request должен быть

2023-02-09 18:25 UTC, Barugoo commented on internal/app/handlers/handler.go
> +		return echo.NewHTTPError(http.StatusInternalServerError, IntServErr)
Здесь и ниже ты возвращаешь ошибки по-разному. Давай определимся какую функцию мы вызываем когда хотим вернуть ошибку (`c.String` или `echo.NewHTTPError`) и будем использовать ее везде, чтобы код выглядел однородно

2023-02-09 18:26 UTC, Barugoo commented on internal/app/handlers/handler.go
> +	fmt.Println(cookie.Value)
Давай уберем

2023-02-09 18:27 UTC, Barugoo commented on internal/app/models/item.go
> +}
У них у всех почти одинаковый набор полей
Давай сделаем единую структуру и будем использовать ее везде.

2023-02-09 18:29 UTC, Barugoo commented on pkg/generator/generator.go
> +		log.Fatalf("generateRandomID error: %v\n", err)
`log.Fatal` у нас внутри вызывает `os.Exit(1)` что тут же прибивает процесс
т.е: никакой код после фатала выполнен не будет, так что в `return` смысла нет

Но вообще мы обычно не фаталим нигде, кроме функции `main()`, и тем более мы не фаталим в вспомогательных функциях или функциях которые учавствую в обработке запроса

2023-02-09 18:31 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +		// шаг 3 — указываем, что каждое видео будет добавлено в транзакцию
видео?)

2023-02-09 18:33 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +		panic(err)
Давай здесь не паниковать, а возвращать ошибку наверх

2023-02-09 18:40 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
>Чтобы определить тип ошибки PostgreSQL, с которой завершился запрос, можно воспользоваться библиотекой github.com/jackc/pgerrcode, в частности pgerrcode.UniqueViolation. В таком случае нужно будет сделать дополнительный запрос к хранилищу, чтобы определить сокращённый вариант URL.

2023-02-09 18:49 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +				return models.Item{}, repositories.ErrNotFound
Давай здесь обернем эту ошибку в что-то поясняющее, потому что в текущей конфигурации у нас метод на добавление записи в хранилку возвращает нот фаунд без каких-либо пояснений - для вызывающего кода это будет выглядеть как бред и этот not found он ожидать не будет:
```go
item, err = p.GetItemByFullURL(ctx, item.FullURL)
if err != nil {
    return models.Item{}, fmt.Errorf("failed to retrieve conflicting row in db: %w", repositories.ErrNotFound)

2023-02-09 18:50 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
уменьшаем вложенность:
```go
if err != nil && !strings.Contains(err.Error(), "duplicate key value violates unique constraint") 
//...
``` 
и так далее

2023-02-09 18:54 UTC, Barugoo commented on internal/app/repositories/inmemory/inmemory.go
> +	return models.Item{}, repositories.ErrNotFound
Чтобы не делать каждый раз при возврате ошибки `models.Item{}` можно сделать так, чтобы структура которую ты возвращаешь в качестве результата возвращалась по указателю, а не по значению:
```go
func (r *Repository) GetItemByID(ctx context.Context, id string) (*models.Item, error) {
//...
return nil, repositories.ErrNotFound

2023-02-09 18:57 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +	item.ShortURL = item.ShortURL + id
Я не совсем понимаю зачем нам вообще поле `ShortURL` если оно дублирует значение поля `ID`
Плюс очень странно, что в одной реализации у тебя айди - это строка из трех символов, а в другой реализации это число.

2023-02-09 18:58 UTC, Barugoo commented on internal/app/repositories/file/file.go
> +	return items, nil
Метод надо реализовать

2023-02-09 19:02 UTC, Barugoo requested changes
Привет! Запишись пожалуйста на 1-1

2023-02-14 11:11 UTC, Barugoo commented on internal/migrations/000001_create_table_short_links.up.sql
> +    full_url  varchar(255) not null ,
short_url varchar(255) not null unique

2023-02-14 11:12 UTC, Barugoo commented on internal/migrations/000001_create_table_short_links.up.sql
> +    full_url  varchar(255) not null ,
http://localhost:8080/dskldsk

dskldsk <-

2023-02-14 11:18 UTC, Barugoo commented on internal/app/models/item.go
> +}
```go
type ShortURL struct {
    ShortURL string `json:"short_url"`
    OriginalURL string `json:"original_url"
    UserID string `json:"-"`
}

2023-02-14 11:21 UTC, Barugoo commented on internal/app/models/item.go
> +type ItemList struct {
type ItemList []Item

2023-02-14 11:22 UTC, Barugoo commented on internal/app/handlers/handler.go
> +	// Собираем мапу айтемсов
Давай унесем аутентификацию в начало хэндлера - нам незачем десериализовать структуру запроса если мы не можем прочитать куку

2023-02-14 11:28 UTC, Barugoo commented on internal/app/handlers/handler.go
> +
package ctxdata

type contextKey string

const contextKeyUserID = "user_id"

func SetUserID(ctx context.Context, userID string) context.Context {
    return context.WithValue(ctx, contextKeyUserID, userID)
}

func GetUserID(ctx context.Context) (string, bool) {
     return ctx.Value(contextKeyUserID).(string)
}

2023-02-14 11:39 UTC, Barugoo commented on internal/app/middlewares/cookie_middleware.go
> +
```go
userID, _ := generator.GenerateRandomID(16)

cookie, err := c.Cookie("user_id")
if err == nil {
    userID = cookie.Value
} 

ctx := ctxdata.SetUserID(c.Request().Context(), userID) 

// проставляем этот контекст в конекст запроса который мы передадим в `next`
```
в хэндлере:
```go
userID, ok := ctxdata.GetUserID(c.Request().Context())
if !ok {
    // bad request
}

2023-02-14 11:53 UTC, Barugoo commented on internal/app/repositories/postgres/postgres.go
> +		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
```go
if err != nil {
    var pgErr pgconn.PgError
    if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
        // then it's unqiue violation
    }
}

2023-02-14 20:40 UTC, AntonNikol commented on internal/app/models/item.go
> +}
Есть просьба сейчас принять работу так, все остальное пофиксил. Кажется, что на 14 итерацию остается времени очень мало и хочу успеть сдать ее вовремя. Эти замечания пофикшу чуть позже

2023-02-14 20:40 UTC, AntonNikol commented
Есть просьба сейчас принять работу так, все кроме  ``` У них у всех почти одинаковый набор полей
Давай сделаем единую структуру и будем использовать ее везде.```  пофиксил. Кажется, что на 14 итерацию остается времени очень мало и хочу успеть сдать ее вовремя. Эти замечания пофикшу чуть позже

2023-02-14 21:56 UTC, Barugoo approved these changes
вроде все гуд, работу принимаю, отлично!

2023-02-14 22:12 UTC, merged