handler DELETE postgres
AntonNikol/go-shortener pull request #22
Opened 2023-02-19 20:44 UTC by AntonNikol

2023-02-21 16:03 UTC, AntonNikol commented
В общем получилось как обычно. fan in реализовать не получилось. По работе с БД и файлом сегодня запушу обновленный код

2023-02-23 07:20 UTC, Barugoo commented on internal/app/repositories/file/file.go
> +func (r *Repository) Delete(ctx context.Context, list []string, userID string) error {
Эта реализация у нас работает синхронно, в этом проблема - по заданию удаление должно идти в фоне

2023-02-23 07:21 UTC, Barugoo requested changes
Привет! Задание не выполнено - нам нужно удалять записи в фоне, то бишь асинхронно по отношению к клиенту. Сейчас клиент обязан дождаться завершения удаления всех урлов прежде чем он получит ответ от нашего сервера. 

Запишись на 1-1, разберем задание

2023-02-27 16:33 UTC, Barugoo commented on internal/workers/worker.go
> +
Очищаем буффер в одном потоке 
Добавляем новые урлы в буффер в N потоков (где N - количество воркеров)
```go
w := WorkerPool{
 	ch:      make(chan task, chCap),
 	ctx:     ctx,
 	storage: storage,
}

flushCh := make(chan struct{})
for i:=0; i<workerCount; i++ {
    go func() {
        for job := range w.ch {
            j.addToBuffer(req, flushCh)
        }
    }()
}
   
go func() {
    ticker := time.NewTicker(period)
    for {
 	select {
 	case <-ticker.C:
 		j.removeBatchStorage()
 	case <-j.ctx.Done():
 		ticker.Stop()
 		j.removeBatchStorage()
 	}
     }
}()

return &w
}

2023-02-27 16:35 UTC, Barugoo commented on internal/workers/worker.go
> +	buffer  map[string][]string
```go
ch      chan *task
buffer []*task

2023-02-27 16:36 UTC, Barugoo commented on internal/workers/worker.go
> +		j.buffer[t.userID] = append(j.buffer[t.userID], v)
просто аппендим в `buffer []task`
после аппенда делаем следующее:
```go
if len(j.buffer) >= j.BufferMaxSize {
    flushCh <- struct{}{}
}

2023-02-27 16:55 UTC, Barugoo commented on internal/app/handlers/handler.go
>  	}
вот это 
```
	body, err := io.ReadAll(c.Request().Body)
	if err != nil {
		return c.String(http.StatusInternalServerError, IntServErr)
	}
	if len(body) == 0 {
		return c.String(http.StatusBadRequest, "Request body is required")
	}
	var itemsRequest []models.ItemList
	err = json.Unmarshal(body, &itemsRequest)
	if err != nil {
		return c.String(http.StatusBadRequest, IntServErr)
	}
```
эквивалентно вот этому:
```go
var itemsRequest []models.ItemList
if err := json.NewDecoder(c.Request().Body).Decode(&itemsRequest); err != nil {
    return c.String(http.StatusBadRequest, "unable to unmarshal body")
}
if len(itemsRequest) == 0 {
    return c.String(http.StatusBadRequest, "zero urls in the passed list")
}

2023-02-27 23:52 UTC, Barugoo approved these changes
Работу принимаю!

2023-03-06 14:39 UTC, merged